### PR TITLE
Workaround problematic tinyMCE editor in jquery-ui sortables scenario

### PR DESCRIPTION
**Pull request by entr**
Repeaters and flexibles in Papi suffer from https://github.com/tinymce/tinymce/issues/2277
Basically to workaround it, editor needs to be removed on sortstart and re-initiated on sortend.

### CODE REVIEW

**Comment by frozzare** [comment]
Please follow the code style in the JavaScript files. I don't have spaces like in the PHP code. So do not do `$.each( ids` do `$.each(ids`.

**Comment by frozzare** [comment]
Camelcase should be used not sneakcase

**Comment by entr** [comment]
No problem, just saw you have eslint rules defined. Plus I also need to add the flexible code too, oops.

**Comment by entr** [comment]
Thanks for merging this but is there a chance to get it released :pray:

**Comment by frozzare** [comment]
Yeah, I will try to get a patch release out soon, did forget about this fix in the last patch release.

**Comment by frozzare** [comment]
@entr https://github.com/wp-papi/papi/releases/tag/v2.4.10

**Comment by entr** [comment]
:bow:

**Pull request merged**
