### PR TITLE
fix WP forms.css and select2 styles conflict

### LINKED ISSUE #105: Strange select overflow causing horizontal scroll on fullhd res
This is WP 4.0.8, papi [#8409cfa](https://github.com/wp-papi/papi/commit/8409cfa0710908ff3d2fdbe1bc962d806f3f10a7) on Google Chrome 45.0.2454.93 (LinuxMint). I can see the select excessive width on firefox too but without the horizontal scroll.

```position: relative; ``` on the direct parent element seems to "fix" it.

papi-select-width

Do you need additional info?

### PR DESCRIPTION
**Pull request by entr**
fixes #105

### CODE REVIEW

**Comment by entr** [comment]
Actually forms.css doesn't conflict. Problem seems to be the following rule
```css
.papi-table tr td input, .papi-table tr td select, .papi-table tr td textarea {
  width: 99.5%;
}
```
overriding `.select2-hidden-accessible` width rule, to be clear.

**Comment by frozzare** [comment]
Won't this fix break the accessibility in select2?

**Comment by entr** [comment]
It just restores vendor's width rule. If we assume select2 author takes care of accessibility then this is fixing it not braking.

**Comment by frozzare** [comment]
Thanks. Just looked at select2 source css and it's the same width.

**Pull request merged**
