### PR TITLE
Search for template files in the child theme first

### PR DESCRIPTION
**Pull request by canufeelit**

### CODE REVIEW

**Comment by frozzare** [comment]
Looks good, but where is your test cases for this?

**Comment by canufeelit** [comment]
Hi, honestly, this is my second pull request and I'm not exactly sure what these tests are. Can you point me at some direction about this?

**Comment by frozzare** [comment]
Look at https://make.wordpress.org/core/handbook/testing/automated-testing/, https://pippinsplugins.com/unit-tests-wordpress-plugins-setting-up-testing-suite/ and then https://github.com/wp-papi/papi/tree/master/tests

**Comment by canufeelit** [comment]
Aren't these tests automatically included in `The Travis CI`?

**Comment by frozzare** [comment]
Yes they are, but there are no automatic tests created for the code you did in your pull request. So what's you need to do is test you code before I merge the pull request, the point of a pull request is to contribute, not giving the plugin author more work.

This is the tests that I want you to do when you do pull requests to this plugin. https://github.com/wp-papi/papi/blob/master/tests/cases/lib/template-test.php#L76

**Comment by canufeelit** [comment]
Sorry, but I really don't understand how this test work and I'm afraid I might break something else in the process. It seems I still have a lot to learn and for now I'll just write an issue, so you can fix it when you have the time. I thought the automated check is enough to be passed for you to make the merge and thats why I did the pull request. Won't happen again, sorry.
Thank you for the info and this awesome plug-in.

**Comment by frozzare** [comment]
No problem. I will test this manually and write a unit test for it. The automatic Travis test is all existing tests that is running to see if the pull request don't break anything but it don't create new tests automatic.




Thank you for your pull request! Glad that you like Papi! 



Med vänlig hälsning,Fredrik

**Comment by frozzare** [comment]
The code works but I think is better to use `locate_template` that will handle this. I will merge your code and change to `locate_template`.

**Comment by frozzare** [comment]
I close this since it's merged now to `2.5-dev` now. https://github.com/wp-papi/papi/commit/2493458a09b0b9ba403fea6eba131f0e0d2ee633

**Pull request closed without merging**
